### ISSUE TITLE
Upper limit is never returned

### ISSUE THREAD

**Issue by riker09** [Gabb1995/insomnia-plugin-randomnumber#3]
https://github.com/Gabb1995/insomnia-plugin-randomnumber/blob/4036912cc6db546bc430a3049f2c0931829eb72b/randomNumber.js#L45

`Math.floor()` should be replaced with `Math.round()`, otherwise the upper limit can never be reached.

**Comment by Gabb1995** [comment]
Thanks, sorry for late reply! Updating it soon.

**Comment by Gabb1995** [comment]
Fixed in latest release.
